name: memora
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.0
  #image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_icon.png
    - assets/images/bea.png
    - assets/images/emi.png
    - assets/images/gyurika.png
    - assets/images/kati.png
    - assets/images/profile.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

  #  > flutter pub run flutter_launcher_icons